### ISSUE TITLE
学习交流

### ISSUE THREAD

**Issue by fntp** [Xarrow/Everything4J#1]
看到作者的代码深感敬佩，想与作者学习交流一番，望成全，

**Comment by Xarrow** [comment]
> 看到作者的代码深感敬佩，想与作者学习交流一番，望成全，

你好 👋

**Comment by fntp** [comment]
大佬，方便加个好友吗，推特或者电报或者wechat

**Comment by Xarrow** [comment]
> 
TG=aHR0cHM6Ly90Lm1lL3ZhcmlhYmxldW5kZWZpbmVkZA==

**Comment by Xarrow** [comment]
> 大佬，方便加个好友吗，推特或者电报或者wechat


TG=aHR0cHM6Ly90Lm1lL3ZhcmlhYmxldW5kZWZpbmVkZA==
